kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hello-app-nfs-noisiel-claim
  namespace: eclair-eclairdemo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-noisiel
