kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hello-app-pvc
  namespace: kube-kubedemo
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
